Cliques = [
  "popular kids",
  "theater nerds",
  "know-it-alls",
  "smart-alecks",
  "wise guys",
  "jocks",
  "fashionistas",
  "stylistas",
  "gossip girls",
  "show-offs",
  "smart-asses",
  "politicos",
  "brainiacs",
  "oafs",
  "band geeks",
  "pretty people",
  "smarty pants",
  "indie kids",
  "goths",
  "swashbucklers",
  "overachievers",
  "nerds",
  "vainglorious",
  "geeks",
  "metalheads",
  "Trekkies",
  "ravers",
  "Beliebers",
  "baby boomers",
  "millenials",
  "queen bees",
  "queers",
  "revolutionaries",
  "free radicals",
  "bros",
  "one percenters",
  "floaters",
  "stoners",
  "feminists",
  "activists",
  "vegetarians",
  "vegans",
  "carnivores",
  "slam poets",
  "Beatniks",
  "hippies",
  "loners",
  "reformers",
  "99 percenters",
  "thespians",
  "skaters",
  "outsiders",
  "hipsters",
  "preps",
  "emo kids",
  "mean girls",
  "rockers",
  "scenesters",
  "punk kids"
  ]

module.exports = {
  Cliques: Cliques
}
