Quotes = [
  "If you judge people, you have no time to love them",
  "Love doesn't make the world go round",
  "At the touch of love everyone becomes a poet",
  "Love is an irresistible desire",
  "This is my commandment",
  "Some desire is necessary to keep life in motion",
  "Strong lives are motivated by dynamic purposes",
  "Nothing in life is to be feared",
  "Just living is not enough",
  "In the book of life, the answers aren't in the back",
  "Time is a great teacher",
  "Never take life seriously",
  "Nobody gets out alive",
  "Call me Ishmael",
  "I was the shadow of the waxwing slain",
  "They say when trouble comes close ranks",
  "Time is not a line but a dimension",
  "Once upon a time",
  "The cold passed reluctantly from the earth",
  "He was born with a gift of laughter",
  "It was a pleasure to burn",
  "He was an old man who fished alone",
  "All this happened, more or less",
  "Stately, plump Buck Mulligan",
  "Once upon a time and a very good time it was",
  "It is a truth universally acknowledged",
  "It was the best of times, it was the worst of times",
  "Life is about making an impact",
  "Two roads diverged in a wood",
  "I want to know God's thoughts",
  "The best time is now",
  "An unexamined life is not worth living",
  "We become what we think about",
  "Eighty percent of success is showing up",
  "Winning isn't everything",
  "Life shrinks or expands in proportion to one’s courage",
  "The best revenge is massive success",
  "The most difficult thing is the decision to act",
  "You miss 100% of the shots you don’t take",
  "An eye for eye only ends up making the whole world blind",
  "Whatever the mind can conceive and believe, the mind can achieve",
  "You can have everything in life that you want",
  "It does not matter how slowly you go so long as you do not stop",
  "Only fools are positive",
  "Time marches on"
]

module.exports = {
  Quotes: Quotes
}
