module.exports = [
  "in a bicycle accident",
  "in a car crash",
  "to a fall",
  "on a trampoline",
  "to a bagel injury",
  "while camping",
  "in a boating accident",
  "when they almost drowned",
  "when they fell from a tree",
  "to a lightning strike",
  "in the fire",
  "in a hurricane",
  "in a landslide",
  "in a car accident",
  "when a knife slipped",
  "in the fall",
  "in a football game",
  "playing baseball",
  "playing rugby",
  "while hiking",
  "mountain climbing",
  "cycling",
  "to frostbite",
  "while skiing",
  "while snowboarding",
  "at Burning Man",
  "to a stress fracture",
  "on Election Night",
  "on their wedding day",
  "on their honeymoon",
  "graduation day",
  "in childbirth",
  "picking apples",
  "on Halloween",
  "at Christmas",
  "on Easter Sunday",
  "that cold day in January",
  "that fated day in spring",
  "on April Fool's day",
  "the fourth of July",
  "on their birthday",
  "at the supermarket",
  "in the ocean",
  "at the lake",
  "that long summer",
  "in the field",
]

