module.exports.wordTypes = {
  animals: require('./animals'),
  bodyParts: require('./body'),
  brands: require('./brands'),
  cities: require('./cities'),
  cliques: require('./cliques'),
  colors: require('./colors'),
  cookingWords: require('./cookingWords'),
  drinkAdjectives: require('./drinkAdjectives'),
  drinks: require('./drinks'),
  foods: require('./foods'),
  furniture: require('./furniture'),
  hurts: require('./waysToGetHurt'),
  interjections: require('./interjections'),
  names: require('./names'),
  prepositions: require('./prepositions'),
  relatives: require('./relatives'),
  rooms: require('./rooms'),
  senseNouns: ["sight", "hearing", "touch", "smell", "taste"],
  senseWords: ["tasted", "smelled", "sounded", "felt", "looked"],
  quotes: require('./shortQuotes'),
  trees: require('./trees'),
  treeAdjectives: require('./treeAdjectives'),
  writings: require('./writingForms'),
}
