var WritingForms = [
  "adventure stories",
  "anecdotes",
  "apologies",
  "autobiographies",
  "biographies",
  "book reviews",
  "brochures",
  "cartoons",
  "character sketches",
  "classified ads",
  "comic strips",
  "complaints",
  "descriptions",
  "diaries",
  "editorials",
  "encyclopedia entries",
  "essays",
  "eulogies",
  "explanations",
  "fables",
  "fairy tales",
  "fantasies",
  "fashion articles",
  "fictions",
  "folklores",
  "ghost stories",
  "how-to-do-it articles",
  "interviews",
  "jokes and riddles",
  "journals",
  "jump rope rhymes",
  "legends",
  "letters",
  "lists",
  "magazine articles",
  "memories",
  "monologues",
  "mysteries",
  "myths",
  "news articles",
  "nonfictions",
  "opinions",
  "pamphlets",
  "parodies",
  "personal experiences",
  "persuasive letters",
  "picture books",
  "plays",
  "poems",
  "proposals",
  "reactions",
  "reports",
  "resumes",
  "retellings",
  "reviews",
  "revisions",
  "satires",
  "scary stories",
  "short stories",
  "science articles",
  "science fictions",
  "sequels",
  "songs",
  "speeches",
  "spoofs",
  "sports columns",
  "spy stories",
  "commercials",
  "tall tales",
  "testimonials",
  "thank you notes",
  "tongue twisters",
  "travel brochures",
  "want ads",
  "wanted posters",
]

module.exports = {
  WritingForms: WritingForms
}
